### ISSUE TITLE
Feedback for incomplete projects

### ISSUE THREAD

**Issue by KALoneNinja** [KALoneNinja/Evaluation-Extension#29]
If there are a lot of fails, there should be feedback added to tell the student that they should check if it will pass before submitting so both of our time isn't wasted.

**Comment by InHoh** [comment]
This would really be useful. Currently there are a lot of students who do nothing more than change the text in the starter code before submitting. They generally have not done enough work to earn "I love your indents", since those indents were there before, and most likely finer advice on embellishments are wasted on them. So I end up removing much of the suggested messages, only to tell them that they need to learn the basics. Most of the time these students have not completed earlier projects.

**Comment by KALoneNinja** [comment]
Okay, it is added. I do have one question though. Should it show up when there are 4 passes and compliments, 3, or 2?
